name: 'dev-full_stack-tf-apply'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Deploy full AWS ECS FX stack 
        run: echo Deploy full AWS ECS FX stack
