name: 'dev-ecs-vpc-tf-apply'

on:
  workflow_dispatch:

jobs:
  tf-apply:
    name: 'tf-apply'
    runs-on: ubuntu-latest
    environment: dev
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: us-east-1
      TF_VAR_env: dev

      # VPC
      TF_VAR_vpc_name: "Fargate FX VPC"
      TF_VAR_cidr: 10.193.36.0/24
      TF_VAR_project_name: "Forex"
      TF_VAR_owner: "Ricardo Fortune"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/dev/vpc

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./environments/dev/vpc

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./environments/dev/vpc

    # Apply the Terraform execution plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./environments/dev/vpc