name: 'dev-full_stack-tf-apply'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Deploy EFS storage and bastion server
        run: echo Deploy EFS storage and bastion server
